<?php
/**
 * Created by PhpStorm.
 * User: a
 * Date: 2019/5/28
 * Time: 18:48
 */

namespace Tests;

use Illuminate\Support\Arr;
use Tests\TestCase as BaseCase;

abstract class ChatCase extends BaseCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $token = $this->setToken();
        $this->requestHeader = Arr::add($this->requestHeader, 'Authorization', 'Bearer '. $token);
    }
}