<?php

namespace Tests;

use App\Models\Chat\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\TestResponse;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, WithFaker;

    protected $requestHeader = [
        'Accept' => 'application/json',
    ];

    protected $responseJsonStructure;

    protected $successStatus = ['status_code' => 200];

    protected $user;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->init();
    }

    public function init()
    {
        Artisan::call('config:clear');
        Artisan::call('migrate');
        $this->responseJsonStructure = ['data', 'time', 'status_code'];
        if(!User::find(1)){
            factory(User::class, 1)->create();
        }
        $this->user = User::find(1);
    }

    public function setToken()
    {
        return auth('api')->login($this->user);
    }

    public function baseVerification(TestResponse $response)
    {
        $response->assertJsonFragment($this->successStatus);
        $response->assertJsonStructure($this->responseJsonStructure);
    }
}
